version: '3'
services:
  postgres-db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres 
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/:ro
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0.25
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=credit-db
      - MYSQL_PASSWORD=root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    networks:
      - my-network

networks:
  my-network: