version: '3'
services:
  postgres-db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres 
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/:ro
    networks:
      - my-network

networks:
  my-network: