server:
  port: 6161

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:password}
  cloud:
    gateway:
      routes:
        - id: register-user
          uri: ${USER_SERVICE_BASE_URL:http://localhost:6170}
          predicates:
            - Path=/user-service/api/v1/register
            - Method=POST
          metadata:
            tokenRequired: false
        - id: login-user
          uri: ${USER_SERVICE_BASE_URL:http://localhost:6170}
          predicates:
            - Path=/user-service/api/v1/login
            - Method=POST
          metadata:
            tokenRequired: false
        - id: create-credit
          uri: ${CREDIT_SERVICE_BASE_URL:http://localhost:6180}
          predicates:
            - Path=/credit-service/api/v1/credit
            - Method=POST
          metadata:
            tokenRequired: true
        - id: get-credits
          uri: ${CREDIT_SERVICE_BASE_URL:http://localhost:6180}
          predicates:
            - Path=/credit-service/api/v1/credit
            - Method=GET
          metadata:
            tokenRequired: true
        - id: get-credit
          uri: ${CREDIT_SERVICE_BASE_URL:http://localhost:6180}
          predicates:
            - Path=/credit-service/api/v1/credit/{credit}
            - Method=GET
          metadata:
            tokenRequired: true
        - id: get-credit-installments
          uri: ${CREDIT_SERVICE_BASE_URL:http://localhost:6180}
          predicates:
            - Path=/credit-service/api/v1/credit/{credit}/installment
            - Method=GET
          metadata:
            tokenRequired: true
        - id: pay-credit-installments
          uri: ${CREDIT_SERVICE_BASE_URL:http://localhost:6180}
          predicates:
            - Path=/credit-service/api/v1/credit/{credit}/installment/{installment}
            - Method=POST
          metadata:
            tokenRequired: true

